### ISSUE TITLE
Slices generation fails

### ISSUE THREAD

**Issue by dilgerma** [Nebulit-GmbH/miro-eventmodeling-discussions#14]
### Discussed in https://github.com/Nebulit-GmbH/miro-eventmodeling-discussions/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **fuat** April  9, 2024</sup>

[buchhaltung.json](https://github.com/Nebulit-GmbH/miro-eventmodeling-discussions/files/14918048/buchhaltung.json)

event_modeling docker run -ti -v $PWD/buchhaltung.json:/app/config.json -v $PWD:/app ghcr.io/dilgerma/nebulit-spring-boot-generator
? Was soll generiert werden? slices
starting commands generation
(node:7) Warning: Accessing non-existent property 'givenAnswers' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7) Warning: Accessing non-existent property '_commandTitle' of module exports inside circular dependency
(node:7) Warning: Accessing non-existent property '_readmodelTitle' of module exports inside circular dependency
? Welcher Slices soll generiert werden? slice: Neuen Kunden hinzufügen
? Sollen Rest Endpunkte generiert werden? Yes
? Zugehöriges Aggregate auswählen? Kunde
┌───────────────────────────────────────────────────┐
│              yo update check failed               │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
node:events:496
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'map')
    at typeImports (/usr/local/lib/node_modules/@dilgerma/generator-nebulit-spring-boot/generators/slices/index.js:474:26)
    at /usr/local/lib/node_modules/@dilgerma/generator-nebulit-spring-boot/generators/slices/index.js:175:35
    at Array.forEach (<anonymous>)
    at module.exports._writeEvents (/usr/local/lib/node_modules/@dilgerma/generator-nebulit-spring-boot/generators/slices/index.js:163:54)
    at module.exports.writeEvents (/usr/local/lib/node_modules/@dilgerma/generator-nebulit-spring-boot/generators/slices/index.js:154:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/@dilgerma/generator-nebulit-spring-boot/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/local/lib/node_modules/@dilgerma/generator-nebulit-spring-boot/node_modules/yeoman-generator/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/@dilgerma/generator-nebulit-spring-boot/node_modules/yeoman-generator/node_modules/run-async/index.js:26:19
    at /usr/local/lib/node_modules/@dilgerma/generator-nebulit-spring-boot/node_modules/yeoman-generator/lib/index.js:425:13
Emitted 'error' event on  instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/@dilgerma/generator-nebulit-spring-boot/node_modules/yeoman-generator/lib/index.js:433:22)
    at process.processImmediate (node:internal/timers:478:21)

Node.js v20.12.1</div>

**Comment by dilgerma** [comment]
Fixed in 0.1.35
